### ISSUE TITLE
module Wobserver.Assets is not available

### ISSUE THREAD

**Issue by OvermindDL1** [shinyscorpion/wobserver#15]
When freshly `mix deps.compile wobserver` this as a dependency, the compilation gives these warnings, and indeed I'm not seeing a `Wobserver.Assets` module in the project?

```elixir
==> wobserver
Compiling 4 files (.ex)
warning: function Wobserver.Assets.html/0 is undefined (module Wobserver.Assets is not available)
  lib/wobserver/web/router/static.ex:21

warning: function Wobserver.Assets.css/0 is undefined (module Wobserver.Assets is not available)
  lib/wobserver/web/router/static.ex:32

warning: function Wobserver.Assets.js/0 is undefined (module Wobserver.Assets is not available)
  lib/wobserver/web/router/static.ex:38

warning: function Wobserver.Assets.license/0 is undefined (module Wobserver.Assets is not available)
  lib/wobserver/web/router/static.ex:43
```

**Comment by OvermindDL1** [comment]
Of course following the Hex install section, not the Manual install section.

**Comment by OvermindDL1** [comment]
Same error if following the Manual Install steps as well.

**Comment by IanLuites** [comment]
Which version of wobserver are you using? Can you check in the deps directory whether `lib/wobserver/assets.ex` exist?

I have trouble reproducing this problem. (I downloaded the 0.1.6 version and assets is included and compiles without problem even within a completely new project.)

**Comment by OvermindDL1** [comment]
I was using `{:wobserver, github: "shinyscorpion/wobserver"},` (I move to hex.pm after initial testing is complete, always start with github).

**Comment by IanLuites** [comment]
Ahw, that explains a lot. The assets are not added to the repo in build form. So using `wobserver` directly from the repo does not work, since it will be missing assets.

**Comment by OvermindDL1** [comment]
> Ahw, that explains a lot. The assets are not added to the repo in build form. So using wobserver directly from the repo does not work, since it will be missing assets.

Should add it to the compile step instead of a separate step.  ^.^

**Comment by IanLuites** [comment]
I'll look into that. (See: #20) Thing is it won't work if people don't do a `npm install` first, or have it installed at all.

For now I updated the readme to warn of the problem.

**Comment by OvermindDL1** [comment]
> I'll look into that. (See: #20) Thing is it won't work if people don't do a npm install first, or have it installed at all.

Hmm, true, we need a simple Elixir javascript bundler, though most of your assets could be easily bundled regardless, hmm...
