### ISSUE TITLE
Manual Instructions incorrect

### ISSUE THREAD

**Issue by OvermindDL1** [shinyscorpion/wobserver#16]
When running through the manual instructions step on the readme the `gulp build` step gives the `gulp: command not found` because the step as typed in is trying to call a global `gulp` command although the project installs a local `gulp` that has to be called via `./node_modules/.bin/gulp`, thus the command should probably be `./node_modules/.bin/gulp build`.

**Comment by IanLuites** [comment]
Updated the build tools and the readme should be up to date again.
