### ISSUE TITLE
External Javascript

### ISSUE THREAD

**Issue by OvermindDL1** [shinyscorpion/wobserver#17]
Manually built and packed assets and got other things ready and it 'mostly' works now it seems, however Load Charts is entirely blank, Memory Allocators are entirely blank, Application only shows the drop-down box and description, it looks like a javascript library is supposed to be making the tables sortable in various other pages, however the javascript (and apparently some fonts) are attempting to be called externally, which does not work on the internal network server I'm running.  ^.^

The traditionally Phoenix way to do it is using its bundler (brunch by default, but can replace with whatever, or a manual one) to bake everything together for ease of use in such situations, though this is not Phoenix based it is still a useful style for such locations as here.  :-)

**Comment by IanLuites** [comment]
Sounds like a good idea.

I never did this, because the external deps were very volatile, but now it might be a good idea.

**Comment by IanLuites** [comment]
Fixed in release v0.1.7.
