### ISSUE TITLE
`mix build` is too top-level

### ISSUE THREAD

**Issue by OvermindDL1** [shinyscorpion/wobserver#20]
Custom mix tasks by Elixir suggestions should be prefixed with the project name, so it should be `mix wobserver.build`.  A simple change and figured I should suggest it before the project gets too far along.  :-)

The reason is though that if multiple libraries include mix tasks, because your task 'is' imported into the projects that depend on this library, then they can conflict or become uncallable or even override what is expected from another library.

If you are wanting to define a new mix task that is not imported into the users project that includes this library then you should use a [mix alias](https://hexdocs.pm/mix/Mix.html#module-aliases) instead.  An example (just add this to the bottom of your `mix.exs` file while adding a `aliases: aliases()` to your `project` list):
```elixir
  defp aliases do
    [
      build: &WobServer.Builder.build/1,
    ]
  end
```
This example would add a new task of the name `build` that is exposed only to this project (and not projects that depend on this project), this task will call the `WobServer.Builder.build/1` function, just like your task gets called in its `run/1`.  :-)

Aliases have a lot of other features (see above link), including calling tasks before or after others, you can, say, override 'compile' so it always calls 'build' first and then the normal 'compile' (that way you do not need to distribute your Assets file but instead it can be built on-the-fly when the dependency is compiled, I'm 'pretty' sure dependency building calls the `compile` alias in mix, but uncertain, would want to check...).

:-)

**Comment by OvermindDL1** [comment]
For note, at this moment trying to run `mix build` from a project that includes this library returns this error:
```elixir
Building wobserver:
  Building web assets...      ** (ErlangError) erlang error: :enoent
    (elixir) lib/system.ex:564: System.cmd("gulp", ["deploy"], [stderr_to_stdout: true])
    lib/mix/tasks/build.ex:39: Mix.Tasks.Build.execute/3
    lib/mix/tasks/build.ex:24: Mix.Tasks.Build.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```
If I happen to add a global `gulp` though then it tries to start accessing a local `./assets` directory for files to concat together.  So first of all 'build' needs to not be so top-level, and if it is designed to be run by dependents then it should both be `wobserver.build` as well as should look in its local directory, not the dependents local directory unless you want them to be able to override the files (in which case a default should be chosen if missing too).  An alias really is likely the proper thing to do here though.  :-)

**Comment by IanLuites** [comment]
Ahw, I think this is again, because you included it from the github repository.

The build and analyze tasks are not exported to other projects. They are actually taken out before packaging. If you really want to use wobserver from github/locally you should do a `mix build` and then take the generated package and use that.

I will look into alias, but for now I like the idea that for development I can just do mix build and that code never leaves the dev environment, as in never ends up in the package, which will happen with alias.

**Comment by IanLuites** [comment]
I added `won't fix` for now. I will still look into it, but for now it is not planned.
