### ISSUE TITLE
Connection lost trouble shooting

### ISSUE THREAD

**Issue by ghost** [shinyscorpion/wobserver#22]
I am trying to use the project, I have a server running phoenix and wobserver.
I have added a list of nodes I would like to connect but I keep getting the "Connection lost" error.
The two machine are in the same subnetwork without any firewall.

I am looking for tips, but also it would be nice to have a little more infos either on the logs or in the webpage on what's going on.

Thanks

**Comment by IanLuites** [comment]
Logging should probably be added, it is something I will look into.

The nodes should be able to connect to each other, there are no error message on the application side? Can you post your config or send it to me? (So I can look over it, see what is happening.)

Are you using the wobserver webserver (build-in-cowboy) or are you using plug mode?

**Comment by ghost** [comment]
I had one server using phoenix one cowboy from the one in phoenix I was trying to access the server with the built in cowboy. I can access the other server wobserver using the web interface.

----

My original idea was to have a server in my private network accessible using a public IP that would be abble to connect to the other nodes, for now I will use a proxy.

**Comment by IanLuites** [comment]
I will close this ticket for now, but I will add extra logging in v0.1.7 (see issue #23), please re-open if that gives us more information.
