### ISSUE TITLE
Discovery of other nodes in a cluster?

### ISSUE THREAD

**Issue by brainlid** [shinyscorpion/wobserver#24]
In following instructions and looking through the source, it appears that the discovery of other nodes is limited to trying to connect to another Wobserver instance? 

I was hoping it might be like Observer where I can have it display the information of other connected/clustered nodes. Is that a possibility? Or does Wobserver have to be installed on every node in the cluster that we might want to inspect?

Because of dependency issues, I created a small node with only Wobserver installed that could join an existing cluster and from there review/monitor all the nodes in the cluster. 

Is this currently possible? If not, is it planned for the future?

**Comment by IanLuites** [comment]
I can look into it for the future, for now I'm going to close this ticket, but I will keep it in mind for the future.

The likely solution would probably still involve installing a more lightweight wobserver backend on all the nodes.
