### ISSUE TITLE
websocket connection fails over SSL. 

### ISSUE THREAD

**Issue by mitcheaton1** [shinyscorpion/wobserver#25]
Locally this works without issue. When hosted using SSL, I have Phoenix forcing SSL, and it seems to break the websocket connection. 

I get "Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS."

I'm using Phoenix channels, and my application doesn't have any socket issues on other parts. Maybe I'm doing something wrong?

**Comment by MaxPower15** [comment]
I also had this issue and ended up modifying the `ws://` in the compiled assets.ex to `wss://`, and that fixed it for me. I'll try to get a PR up soon to fix this based on the page's protocol.

**Comment by MaxPower15** [comment]
Related to this, if you visit the page over https, the https://www.chartjs.org/assets/Chart.min.js file will timeout because it hangs over https at that domain. At least, it does for me. We can switch this to use a public CDN that supports https instead.
