### ISSUE TITLE
How to start wobserver only in development.

### ISSUE THREAD

**Issue by CrowdHailer** [shinyscorpion/wobserver#26]
I have wobserver working in my application, However I want it to only run when I need it. 

My solution was to remove `:wobserver` from the applications list in mix.exs. When I need wobserver I start an iex session on the node and call `Application.ensure_all_started(:wobserver)`. However doing this does and the visiting the wobserver port and I get the error that the site cannot be reached. Apart from removing wobserver from my applications list I have made no change to the setup that was working.

**Comment by IanLuites** [comment]
You could configure `:wobserver` to start in [plug mode](https://github.com/shinyscorpion/wobserver#mode-plug) and then only in dev start it in [standalone mode](https://github.com/shinyscorpion/wobserver#mode-standalone).

That should make `:wobserver` only available in dev mode and in other modes it will not open any ports or do any analyzing.

**Comment by IanLuites** [comment]
I'll mark it as resolved, if there is more needed let me know.
