### ISSUE TITLE
Asset paths require trailing slash to be present in the URL

### ISSUE THREAD

**Issue by mspanc** [shinyscorpion/wobserver#27]
I have added wobserver 0.1.5 to my phoenix app.

My config is

```elixir
config :wobserver,
  mode: :plug,
  remote_url_prefix: "/wobserver"
```

and I have added `forward "/wobserver", Wobserver.Web.Router` to the router. 

It seems that if I open

`http://localhost:4060/wobserver/` (notice slash at the end) it works fine but if I omit the last slash it tries to fetch assets from `http://localhost:4060/app.js` etc.

**Comment by IanLuites** [comment]
This should be fixed in version 0.1.6 released a while back.
