### ISSUE TITLE
Assets should be loaded over https if site is using SSL

### ISSUE THREAD

**Issue by mspanc** [shinyscorpion/wobserver#28]
I have launched today wobserver as a part of my phoenix app that uses https but it fails to load with the following error in the browser:

> Mixed Content: The page at 'https://myapp.com/monitor/wobserver/' was loaded over HTTPS, but requested an insecure script 'http://www.kryogenix.org/code/browser/sorttable/sorttable.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by mspanc** [comment]
Ok it seems it was already fixed in https://github.com/shinyscorpion/wobserver/issues/7

**Comment by IanLuites** [comment]
Yep, should have been fixed in version 0.1.6.
