### ISSUE TITLE
Doesn't work with distillery releases

### ISSUE THREAD

**Issue by doughsay** [shinyscorpion/wobserver#3]
I'm giving this a shot in one of our elixir applications, and it works great in standalone mode and plug mode when running locally.  But when we deploy to stage and prod, we use [distillery](https://github.com/bitwalker/distillery) releases.  I think the distillery release breaks the way wobserver serves the index.html, because the file is not included in the release.  This is the error we get:

```
Elixir.File.Error: could not read file stats "deps/wobserver/assets/index.html": no such file or directory
  File "lib/file.ex", line 289, in File.stat!/2
  File "lib/plug/adapters/cowboy/conn.ex", line 38, in Plug.Adapters.Cowboy.Conn.send_file/6
  File "lib/plug/conn.ex", line 429, in Plug.Conn.send_file/5
  File "lib/wobserver/web/router/static.ex", line 1, in Wobserver.Web.Router.Static.plug_builder_call/2
  File "lib/plug/router/utils.ex", line 91, in Plug.Router.Utils.forward/4
  File "lib/wobserver/web/router.ex", line 1, in Wobserver.Web.Router.plug_builder_call/2
  File "lib/phoenix/router/route.ex", line 154, in Phoenix.Router.Route.forward/4
  File "lib/phoenix/router.ex", line 261, in API.Router.dispatch/2
```

Any chance you could give distillery a shot to see how we could get around this?

**Comment by IanLuites** [comment]
I will have a look. It is already possible to set the directory of the assets manually. Might be a quickfix for now. I'll check to see what distillery does with extra files and update.

For now you can manually copy the assets and set the directory by settings in the config:
```elixir
config :wobserver,
  assets: ""
```

So if you copy the complete assets directory (including name) to for example a directory that is called *wobserver* the config would be:
```elixir
config :wobserver,
  assets: "wobserver/"
```
(Your folder structure would then be: `${project-dir}/wobserver/assets/index.html`.)

**Comment by doughsay** [comment]
Thanks, that helps! I'll give it a try.

**Comment by IanLuites** [comment]
I just made a pull request, where I rewrote the assets management. (They now get baked in.)

I just have to run some tests and try a test project with distillery and then I can merge.

**Comment by IanLuites** [comment]
Merged, packaged, and uploaded to hex. Version [0.1.5](https://hex.pm/packages/wobserver) is now available and should work without any problems with distillery release. (Just do a `mix deps.update wobserver`.)

**Note:** Please remove the assets option from the config again or set it to `false`. It is only meant for debugging and might actually interfere with distillery releases.
