### ISSUE TITLE
The configurable security setup doesn't actually work

### ISSUE THREAD

**Issue by notriddle** [shinyscorpion/wobserver#32]
This is in my `config.exs` file:

```elixir
config :wobserver,
  mode: :plug,
  remote_url_prefix: "/wobserver",
  security: BorsNG.WobserverSecurity
```

This is my authenticate function:

```elixir
defmodule BorsNG.WobserverSecurity do
  @spec authenticate(Conn.t) :: Conn.t
  def authenticate(conn) do
    raise "HERE"
  end
end
```

It doesn't reach the `raise "HERE"` line when I open the wobserver page.

This is because the module attributes are evaluated at build-time, which uses the files in "wobserver"'s configuration, not in the dependent modules.

**Comment by andrewtimberlake** [comment]
When changing config for a compiled library you need to have the library recompiled. This can be done by touching the library mix.exs file.
`touch deps/wobserver/mix.exs` should trigger the correct recompile.
You might need to touch your own config.exs file as well.
