### ISSUE TITLE
Use nodes in combination with load balancer

### ISSUE THREAD

**Issue by nulian** [shinyscorpion/wobserver#34]
Was wondering how to configure the nodes section when you have like 3 nodes behind a load balancer which you can't directly access though they can connect with each other off-course. Was expecting that if you configure the nodes you can see the web interface through 1 node and that one connects to the other nodes with the switcher. Maybe my view of how the node version should work isn't correct.

Was trying to configure it in combination with the plug mode. But then when I switched I got a lot of /ws endpoint not found errors on the webserver side.

**Comment by toddharding** [comment]
Hi, i'm experiencing a similar issue running Wobserver on 4 nodes behind a load balancer

The two main errors are:

On first page load:
```
WebSocket connection to 'ws://path.to.service/wobserver/ws' failed: Error during WebSocket handshake: Unexpected response code: 204
``` 

And when selecting a different node:

```
Uncaught (in promise) TypeError: Cannot read property 'elixir_version' of undefined
    at display_system (app.js:11)
```

If I connect to a static node ip and browse to Wobserver then the page reports web socket connectivity correctly, but if I switch node with the switch node button it doesn't actually switch nodes, it just changes the "Connected to:" string to the name/ip of the target node.

Please let me know if you need anymore info.

Thanks

**Comment by IanLuites** [comment]
This should have worked, seems like the sockets are misbehaving.

We also have wobserver running behind a load balancer, but the websockets don't always behave properly.

Websocket library and functionality have been changed in the rewrite, so I'm leaving it up to that.
