### ISSUE TITLE
Remove dependency on third-party assets

### ISSUE THREAD

**Issue by mspanc** [shinyscorpion/wobserver#35]
At the moment seems that https://www.chartjs.org/assets/Chart.min.js is not responding which prevents wobserver UI from loading. Not sure if their SSL is broken (http://www.chartjs.org/assets/Chart.min.js works fine) or they don't support SSL at all, but bundling all required JS instead of relying on third-party services IMO makes more sense, especially in such kind of service as wobserver.

**Comment by mgwidmann** [comment]
its also a bit odd to me that everything gets compiled into that `Assets` module... whats wrong with building them into the `priv` directory and serving them from there... I did this exact technique with my package https://github.com/mgwidmann/flames

**Comment by IanLuites** [comment]
Should already be working. Assets have been build in since a few versions ago, even the Chart one.

There is nothing wrong he priv directory, but that was not how it was originally setup.

Improved system is available in the rewrite.
