### ISSUE TITLE
How to protect "/wobserver" (plug mode)?

### ISSUE THREAD

**Issue by schnittchen** [shinyscorpion/wobserver#40]
Hello,

I want to protect everything below /wobserver from unauthorized users. So far I have tried

* basic auth
* cookie based authorization with a plug

In both cases I hit the same dead end: the required cookie/header was not being sent at all below /wobserver/api. I suspect this is an idiosyncrasy of the javascript "fetch" API that is being used.

I found references to an undocumented security feature which, as I understand it, is needed for inter-node communication (and I only have one node for the forseeable future). Will this feature also authorize users? Otherwise, is there a workaround for the problem with cookies and certain headers not being sent?

**Comment by IanLuites** [comment]
Sadly enough security was a afterthought, since it was originally only for internal stage use.

The rewrite tackles security (incl: authorization) from the start. I won't be back porting it to 0.1, since the 0.2 should be compatible.
