### ISSUE TITLE
Security issue when displaying process state

### ISSUE THREAD

**Issue by sadraskol** [shinyscorpion/wobserver#43]
Hi!

I was inspecting the state of my process that contained some content from a blog post, when suddenly I saw:

![capture du 2017-07-05 19-40-41](https://user-images.githubusercontent.com/2914331/27877165-f011e852-61b9-11e7-9589-06581c5f1a05.png)

The state of the process is interpreted directly in the html, which could lead to a possible code injection problem. If I had some `script` tags in it, it would have been evaluated, god knows what could have happened.

I'm using version 0.1.7 of wobserver.
I can't issue a PR right now with my sucky internet, but if you want to correct the misbehavior, the code involved is around [here](https://github.com/shinyscorpion/wobserver/blob/0114ccf6c0e686e505efb92d9dc7388ee920e057/src/js/interface/process_detail.js#L75).

I might sound rude, but I like this software, I'm not blaming anyone :hugs:

**Comment by IanLuites** [comment]
Thank you, this is indeed a security issue. Fixed in 0.1.8
